#ifndef IOSSERVICE_GLOBAL_H
#define IOSSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOUNTSERVICE_LIBRARY)
#define MOUNTSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#define MOUNTSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IOSSERVICE_GLOBAL_H
